name: gmm
channels:
- conda-forge
dependencies:
- pip
- jupyter
- matplotlib
- notebook
- numpy
- opencv
- pytest
- python=3.10
- scikit-image
- scikit-learn
- setuptools

- pip:
  - git+https://github.com/jdoepfert/roipoly.py


